// Gerado automaticamente por scripts/copiar-imagens.js a partir das fotos em CATEGORIAS/.
// Mapeia slug do produto -> caminho da imagem em /public.

export const imagensProduto: Record<string, string> = {
  "carteira-slim-couro-personalizada": "/images/produtos/porta-cartao/carteira-slim-couro-personalizada-01.jpeg",
  "shoulder-bag-tecido-personalizada": "/images/produtos/bolsas/shoulder-bag-tecido-personalizada-01.jpeg",
  "pochete-lona-personalizada": "/images/produtos/bolsas/pochete-lona-personalizada-01.jpeg",
  "bolsa-lona-crua-personalizada": "/images/produtos/bolsas/bolsa-lona-crua-personalizada-01.png",
  "bolsa-lona-preta-personalizada": "/images/produtos/bolsas/bolsa-lona-preta-personalizada-01.png",
  "bolsa-atheta-personalizada-1": "/images/produtos/bolsas/bolsa-atheta-personalizada-1-01.jpeg",
  "bolsa-atheta-personalizada-2": "/images/produtos/bolsas/bolsa-atheta-personalizada-2-01.jpeg",
  "shoulder-bag-neoprene-personalizada": "/images/produtos/bolsas/shoulder-bag-neoprene-personalizada-01.jpeg",
  "bolsa-lona-alca-pu-personalizada": "/images/produtos/bolsas/bolsa-lona-alca-pu-personalizada-01.jpeg",
  "bolsa-transporte-roupas-personalizada": "/images/produtos/bolsas/bolsa-transporte-roupas-personalizada-01.jpeg",
  "mochilao-personalizado": "/images/produtos/bolsas/mochilao-personalizado-01.jpeg",
  "ecobag-personalizada": "/images/produtos/bolsas/ecobag-personalizada-01.jpeg",
  "bolsa-puffer-personalizada": "/images/produtos/bolsas/bolsa-puffer-personalizada-01.jpeg",
  "tote-bag-personalizada": "/images/produtos/bolsas/tote-bag-personalizada-01.jpeg",
  "tote-bag-black-personalizada": "/images/produtos/bolsas/tote-bag-black-personalizada-01.jpeg",
  "tote-minimalista-personalizada": "/images/produtos/bolsas/tote-minimalista-personalizada-01.jpeg",
  "necessaire-puffer-personalizada": "/images/produtos/necessaire/necessaire-puffer-personalizada-01.jpeg",
  "necessaire-cristal-personalizada": "/images/produtos/necessaire/necessaire-cristal-personalizada-01.jpeg",
  "necessaire-couro-personalizada": "/images/produtos/necessaire/necessaire-couro-personalizada-01.jpeg",
  "porta-estetoscopio-personalizado-1": "/images/produtos/necessaire/porta-estetoscopio-personalizado-1-01.jpeg",
  "porta-estetoscopio-personalizado-2": "/images/produtos/necessaire/porta-estetoscopio-personalizado-2-01.jpeg",
  "porta-fone-personalizado": "/images/produtos/necessaire/porta-fone-personalizado-01.jpeg",
  "bolsa-neoprene-personalizada": "/images/produtos/neoprene/bolsa-neoprene-personalizada-01.jpg",
  "lixeira-carro-personalizada": "/images/produtos/neoprene/lixeira-carro-personalizada-01.jpg",
  "caneca-porcelana-biona-300ml-personalizada": "/images/produtos/porcelanas/caneca-porcelana-biona-300ml-personalizada-01.jpg",
  "caneca-porcelana-100ml-personalizada": "/images/produtos/porcelanas/caneca-porcelana-100ml-personalizada-01.jpg",
  "caneca-porcelana-interior-alca-colorida-personalizada": "/images/produtos/porcelanas/caneca-porcelana-interior-alca-colorida-personalizada-01.jpg",
  "xicara-petit-pires-90ml-personalizada": "/images/produtos/porcelanas/xicara-petit-pires-90ml-personalizada-01.jpg",
  "xicara-pires-porcelana-180ml-personalizada": "/images/produtos/porcelanas/xicara-pires-porcelana-180ml-personalizada-01.jpg",
  "caneca-porcelana-alca-coracao-personalizada": "/images/produtos/porcelanas/caneca-porcelana-alca-coracao-personalizada-01.jpg",
  "caneca-porcelana-fall-350ml-personalizada": "/images/produtos/porcelanas/caneca-porcelana-fall-350ml-personalizada-01.jpg",
  "porta-cartao-couro-personalizado-1": "/images/produtos/porta-cartao/porta-cartao-couro-personalizado-1-01.jpeg",
  "porta-cartao-sintetico-personalizado": "/images/produtos/porta-cartao/porta-cartao-sintetico-personalizado-01.jpeg",
  "porta-cartao-costurado-personalizado": "/images/produtos/porta-cartao/porta-cartao-costurado-personalizado-01.jpeg",
  "porta-notas-personalizado": "/images/produtos/porta-cartao/porta-notas-personalizado-01.jpeg",
  "porta-cartao-couro-personalizado-2": "/images/produtos/porta-cartao/porta-cartao-couro-personalizado-2-01.jpeg",
  "porta-tablet-personalizado-1": "/images/produtos/porta-documentos/porta-tablet-personalizado-1-01.jpeg",
  "porta-tablet-personalizado-2": "/images/produtos/porta-documentos/porta-tablet-personalizado-2-01.jpeg",
  "pasta-executiva-personalizada": "/images/produtos/porta-documentos/pasta-executiva-personalizada-01.jpeg",
  "porta-documentos-personalizado-1": "/images/produtos/porta-documentos/porta-documentos-personalizado-1-01.jpeg",
  "porta-documentos-personalizado-2": "/images/produtos/porta-documentos/porta-documentos-personalizado-2-01.jpeg",
  "relogio-azulejo-personalizado": "/images/produtos/relogio/relogio-azulejo-personalizado-01.jpg",
  "squeeze-aluminio-efeito-magico-500ml-personalizado": "/images/produtos/squeeze/squeeze-aluminio-efeito-magico-500ml-personalizado-01.jpg",
  "squeeze-termico-tampa-emborrachada-900ml-personalizado": "/images/produtos/squeeze/squeeze-termico-tampa-emborrachada-900ml-personalizado-01.jpg",
  "squeeze-500ml-tipo-nike-personalizado": "/images/produtos/squeeze/squeeze-500ml-tipo-nike-personalizado-01.jpg",
  "squeeze-vidro-fresh-400ml-personalizado": "/images/produtos/squeeze/squeeze-vidro-fresh-400ml-personalizado-01.jpg",
  "copo-termico-500ml-personalizado": "/images/produtos/termicos/copo-termico-500ml-personalizado-01.jpg",
  "garrafa-termica-420ml-display-temperatura-personalizada": "/images/produtos/termicos/garrafa-termica-420ml-display-temperatura-personalizada-01.jpg",
  "caneca-chopp-termica-709ml-personalizada": "/images/produtos/termicos/caneca-chopp-termica-709ml-personalizada-01.jpg",
  "copo-termico-350ml-personalizado": "/images/produtos/termicos/copo-termico-350ml-personalizado-01.png",
  "caneca-termica-canudo-600ml-personalizada": "/images/produtos/termicos/caneca-termica-canudo-600ml-personalizada-01.jpg",
  "caneca-termica-canudo-glitter-1-2l-personalizada": "/images/produtos/termicos/caneca-termica-canudo-glitter-1-2l-personalizada-01.jpg",
  "taca-gin-termica-degrade-personalizada": "/images/produtos/termicos/taca-gin-termica-degrade-personalizada-01.jpg",
  "copo-termico-coffee-510ml-personalizado": "/images/produtos/termicos/copo-termico-coffee-510ml-personalizado-01.jpg",
  "caneca-termica-cerveja-350ml-personalizada": "/images/produtos/termicos/caneca-termica-cerveja-350ml-personalizada-01.jpg",
  "garrafa-termica-500ml-personalizada": "/images/produtos/termicos/garrafa-termica-500ml-personalizada-01.jpg",
  "toalha-lavabo-29x45-personalizada": "/images/produtos/toalha/toalha-lavabo-29x45-personalizada-01.jpg",
  "toalha-lavabinho-21x38-personalizada": "/images/produtos/toalha/toalha-lavabinho-21x38-personalizada-01.jpg",
  "jogo-americano-personalizado": "/images/produtos/variados/jogo-americano-personalizado-01.jpeg",
  "porta-celular-plastico-personalizado": "/images/produtos/variados/porta-celular-plastico-personalizado-01.jpeg",
  "chaveiro-couro-personalizado": "/images/produtos/variados/chaveiro-couro-personalizado-01.jpeg",
  "porta-tag-mala-botao-personalizado": "/images/produtos/variados/porta-tag-mala-botao-personalizado-01.jpeg",
  "porta-tag-mala-personalizado": "/images/produtos/variados/porta-tag-mala-personalizado-01.jpeg",
  "mouse-pad-personalizado": "/images/produtos/variados/mouse-pad-personalizado-01.jpeg",
  "porta-oculos-personalizado-1": "/images/produtos/variados/porta-oculos-personalizado-1-01.jpeg",
  "chaveiro-airtag-personalizado": "/images/produtos/variados/chaveiro-airtag-personalizado-01.jpeg",
  "porta-oculos-personalizado-2": "/images/produtos/variados/porta-oculos-personalizado-2-01.jpeg",
  "porta-vinho-personalizado": "/images/produtos/variados/porta-vinho-personalizado-01.jpeg",
  "mascara-dormir-personalizada": "/images/produtos/variados/mascara-dormir-personalizada-01.jpeg",
  "caneca-chopp-vidro-475ml-fosca-personalizada": "/images/produtos/vidro/caneca-chopp-vidro-475ml-fosca-personalizada-01.jpg",
  "caneca-chopp-vidro-340ml-transparente-personalizada": "/images/produtos/vidro/caneca-chopp-vidro-340ml-transparente-personalizada-01.jpg",
  "caneca-chopp-vidro-475ml-transparente-personalizada": "/images/produtos/vidro/caneca-chopp-vidro-475ml-transparente-personalizada-01.jpg",
  "caneca-chopp-vidro-340ml-fosca-personalizada": "/images/produtos/vidro/caneca-chopp-vidro-340ml-fosca-personalizada-01.jpg",
  "caneca-vidro-320ml-transparente-personalizada": "/images/produtos/vidro/caneca-vidro-320ml-transparente-personalizada-01.jpg",
  "copo-whisky-vidro-266ml-personalizado": "/images/produtos/vidro/copo-whisky-vidro-266ml-personalizado-01.jpg",
  "taca-vidro-300ml-fosca-personalizada": "/images/produtos/vidro/taca-vidro-300ml-fosca-personalizada-01.jpg",
  "taca-vidro-300ml-transparente-personalizada": "/images/produtos/vidro/taca-vidro-300ml-transparente-personalizada-01.jpg",
  "copo-dose-vidro-48ml-personalizado": "/images/produtos/vidro/copo-dose-vidro-48ml-personalizado-01.jpg",
};

export function getImagemProduto(slug: string): string | undefined {
  return imagensProduto[slug];
}
